change color card
Boommmeran/team-five pull request #52
Opened 2024-02-10 12:45 UTC by LidiiaZaichenko

2024-02-10 13:32 UTC, Boommmeran requested changes

2024-02-10 13:32 UTC, Boommmeran commented on src/components/Card/Card.styled.jsx
> +    props.priority === 'high'
Тут swith треба зробити

2024-02-11 08:02 UTC, LidiiaZaichenko commented
виправила

2024-02-11 08:15 UTC, Boommmeran approved these changes

2024-02-11 08:15 UTC, merged